### ISSUE TITLE
Sinks, sources, sanitizers

### ISSUE THREAD

**Issue by StefanMich** [SW10IoT/pyt#25]
FlaskEngine needs to be able to recognize these concepts

JSON file where sinks, sources and sanitizers are defined.

**Comment by StefanMich** [comment]
currently implemented as just lists of keywords
this is a fragile implementation!

source = input
catches: "input()", "notinput()"

**Comment by Thalmann** [comment]
Undersøg om parametre har indflydelse på sink, sources par

Kig på EIR
