### ISSUE TITLE
Parameterize LHSVisitor and VarsVisitor

### ISSUE THREAD

**Issue by Thalmann** [SW10IoT/pyt#31]
Use visitors that fit the analysis

for instance a visitor for variables like VarsVisitor or a visitor for expressions, etc

**Comment by StefanMich** [comment]
Adskil visitors, så kun labelvisitor er i CFG

Analyse skal så operere på cfg.nodes og lave den korrekte operation (LHS, vars, etc) på hver node

**Comment by Thalmann** [comment]
SUCCESS
